FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
COPY packages/shared-types ./packages/shared-types
COPY apps/api ./apps/api
RUN npm ci
RUN npm run build:shared
RUN npm run build:api

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/apps/api/dist ./dist
COPY --from=builder /app/apps/api/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
EXPOSE 5000
CMD ["node", "dist/server.js"]
